before_install:
   - mkdir build
   - cd build
   - echo Installing packages
   - sudo apt-get install flex texinfo binutils build-essential -qq > /dev/null 2> /dev/null
   - echo Installing GCC - Running Script
   - sudo ../tools/rockboxdevgcc.sh > /dev/null 2>/dev/null
   - cd /tmp/rbdev-build/gcc-4.4.4/
   - echo Configuring
   - CFLAGS=-U_FORTIFY_SOURCE ./configure --prefix=/usr/local --target=arm-elf-eabi --enable-languages=c --disable-libssp --disable-docs
   - echo Making
   - make
   - make install
   - echo "Configuring Rockbox"
   - ../tools/configurequiet > /dev/null

install: echo "DEPENDENCIES INSTALLED YAY"

script: make

language: c

env:
   matrix:
      - BUILDTYPE='N'
      - BUILDTYPE='B'
   global:
      - BUILDFOR=62
