before_install:
   - mkdir build
   - cd build
   - echo Installing packages
   - sudo apt-get install flex texinfo build-essential -qq > /dev/null 2> /dev/null
   - echo Installing Binutils - Running Script
   - sudo ../tools/rockboxdevbinutils.sh > /dev/null 2>/dev/null
   - echo Installing GCC - Running Script
   - sudo ../tools/rockboxdevgcc.sh > /dev/null 2>/dev/null
   - cd /tmp/rbdev-build/gcc-4.4.4/
   - echo Configuring
   - CFLAGS=-U_FORTIFY_SOURCE ./configure --prefix=/usr/local --target=arm-elf-eabi --disable-werror -q > /dev/null
   - echo Making
   - make -q
   - sudo make install -q
   - echo "Configuring Rockbox"
   - ../tools/configurequiet > /dev/null

install: echo "DEPENDENCIES INSTALLED YAY"

script: sudo make

language: c

env:
   matrix:
      - BUILDTYPE='N'
      - BUILDTYPE='B'
   global:
      - BUILDFOR=62
