before_install:
   - mkdir /tmp/builddeps
   - cd /tmp/builddeps
   - sudo apt-get install wget gcc bzip2 gzip make patch texinfo automake libtool autoconf flex bison -qq > /dev/null 2>/dev/null
   - wget -O binutils.tar.bz2 http://www.nic.funet.fi/pub/gnu/ftp.gnu.org/pub/gnu/binutils/binutils-2.20.1.tar.bz2 > /dev/null
   - wget -O binutils-patch http://www.rockbox.org/gcc/binutils-2.20.1-ld-thumb-interwork-long-call.diff > /dev/null
   - tar xjf binutils.tar.bz2 > /dev/null
   - cd binutils-2.20.1
   - patch -p1 < "../binutils-patch" > /dev/null
   - cd ../
   - wget -O gcc.tar.bz2 http://www.nic.funet.fi/pub/gnu/ftp.gnu.org/pub/gnu/gcc/gcc-4.4.4/gcc-core-4.4.4.tar.bz2 > /dev/null
   - wget -O gcc-patch http://www.rockbox.org/gcc/rockbox-multilibs-noexceptions-arm-elf-eabi-gcc-4.4.2_1.diff > /dev/null
   - tar xjf gcc.tar.bz2 > /dev/null
   - cd gcc-4.4.4
   - patch -p1 < "../gcc-patch" > /dev/null
   - cd ../
   - mkdir build-gcc
   - cd gcc-4.4.4
   - wget -O gmp.tar.bz2 http://www.nic.funet.fi/pub/gnu/ftp.gnu.org/pub/gnu/gmp/gmp-4.3.2.tar.bz2 > /dev/null
   - wget -O mpfr.tar.bz2 http://www.nic.funet.fi/pub/gnu/ftp.gnu.org/pub/gnu/mpfr/mpfr-2.4.2.tar.bz2 > /dev/null
   - wget -O mpc.tar.gz http://www.multiprecision.org/mpc/download/mpc-0.8.1.tar.gz > /dev/null
   - tar xjf gmp.tar.bz2 > /dev/null
   - tar xjf mpfr.tar.bz2 > /dev/null 
   - tar xzf mpc.tar.gz > /dev/null
   - ln -s gmp-4.3.2 gmp
   - ln -s mpfr-2.4.2 mpfr
   - ln -s mpc-0.8.1.tar.gz mpc
   - cd ../
   - mkdir build-binutils
   - cd build-binutils
   - export FAIL="binutils"
   - CFLAGS=-U_FORTIFY_SOURCE ../binutils-2.20.1/configure --target=arm-elf-eabi --prefix=/usr/local --enable-languages=c --disable-libssp --disable-docs --disable-werror > /dev/null 2>/dev/null
   - make -j > /dev/null 2>/dev/null
   - sudo make install >/dev/null 2>/dev/null
   - cd ../
   - cd build-gcc
   - export FAIL="gcc"
   - CFLAGS=-U_FORTIFY_SOURCE ../gcc-4.4.4/configure --target='arm-elf-eabi' --prefix='/usr/local' --enable-languages=c --disable-libssp --disable-docs > /dev/null 2> /dev/null
   
install: sudo make -j100 > /dev/null 2>/dev/null

before_script:
   - sudo make install > /dev/null 2>/dev/null
   - cd ../
   - cd ~/builds/whiskers75/rockbox
   - mkdir build
   - cd build
   - export FAIL="rockbox"
   - ../tools/configurequiet >/dev/null 2>/dev/null
   - clear

script: make 



language: c

env:
   matrix:
      - BUILDTYPE='N' BUILDFOR=62
      - BUILDTYPE='N' BUILDFOR=25
