before_install:
   - mkdir build
   - cd build
   - echo Installing packages
   - sudo apt-get install flex texinfo binutils build-essential -qq > /dev/null 2> /dev/null
   - echo Installing GCC - Running Script
   - sudo ../tools/rockboxdevgcc.sh > /dev/null 2>/dev/null
   - cd /tmp/rbdev-build/gcc-4.4.4/
   - echo Configuring
   - CFLAGS=-U_FORTIFY_SOURCE ./configure --prefix=/usr/local --target=arm-elf-eabi > /dev/null 2>/dev/null
   - echo Making
   - export export LD_LIBRARY_PATH=/usr/local/gmp-4.1.3/lib:/usr/local/mpfr-2.3.2/lib:$LD_LIBRARY_PATH
   - make > /dev/null 2>/dev/null
   - sudo make install > /dev/null
   - echo "Configuring Rockbox"
   - ../tools/configurequiet > /dev/null

install: echo "DEPENDENCIES INSTALLED YAY"

script: sudo make

language: c

env:
   matrix:
      - BUILDTYPE='N'
      - BUILDTYPE='B'
   global:
      - BUILDFOR=62
