before_install:
   - mkdir build
   - cd build
   - echo Installing packages
   - sudo apt-get install flex texinfo build-essential binutils -qq > /dev/null 2> /dev/null
   - echo Installing Binutils - Running Script
   - sudo ../tools/rockboxdevbinutils.sh > /dev/null 2>/dev/null
   - echo Installing GCC - Running Script
   - sudo ../tools/rockboxdevgcc.sh 
   - cd $GCCDIR
   - CFLAGS=-U_FORTIFY_SOURCE ../gcc-4.4.4/configure --target=$target --prefix=$prefix --enable-languages=c --disable-libssp --disable-docs $configure_params
   - make
   - sudo make install
   - echo "Configuring Rockbox"
   - ../tools/configurequiet > /dev/null 2>/dev/null

install: echo "DEPENDENCIES INSTALLED YAY"

script: sudo make

language: c

env:
   matrix:
      - BUILDTYPE='N'
      - BUILDTYPE='B'
   global:
      - BUILDFOR=62
