before_install:
   - sudo mv compiler.tar / && cd / && sudo tar -xvf compiler.tar
   - echo "Running configure"
   - cd ~/builds/whiskers75/rockbox
   - mkdir build && cd build
   - ../tools/configurequiet > /dev/null

install: echo "DEPENDENCIES INSTALLED YAY"

script: make

language: c
