before_install:
   - mkdir build
   - cd build
   - # Installing packages
   - sudo apt-get install flex texinfo binutils build-essential -qq > /dev/null 2> /dev/null
   - export BUILDFOR=62
   - # Installing GCC
   - sudo ../tools/rockboxdevgcc.sh > /dev/null 2>/dev/null
   - echo "Running configure"
   - ../tools/configurequiet > /dev/null

install: echo "DEPENDENCIES INSTALLED YAY"

script: make

language: c

env:
   - BUILDTYPE='N'
   - BUILDTYPE='B'
