install: sudo apt-get install texinfo flex -qq && sudo tools/rockboxdev.sh > /dev/null 2>/dev/null

before_script:
   - mkdir build
   - tools/configurequiet > /dev/null 2>/dev/null

script: make

language: c

env:
   matrix:
      - BUILDTYPE='N' BUILDFOR=62
      - BUILDTYPE='B' BUILDFOR=62
      - BUILDTYPE='N' BUILDFOR=63
      - BUILDTYPE='B' BUILDFOR=63
      - BUILDTYPE='N' BUILDFOR=61
      - BUILDTYPE='B' BUILDFOR=61
