install: printf "\nBUILDING whiskers75/rockbox:$TRAVIS_BRANCH $x\nJOB NO $TRAVIS_JOB_ID\nCOMMIT $TRAVIS_COMMIT\nPULL REQUEST $TRAVIS_PULL_REQUEST\n\n\nINSTALLING BUILD DEPENDENCIES FOR ARM TARGETS\n" && sudo travis/install.sh

before_script: mkdir build && cd build && printf "\n\nCONFIGURING whiskers75/rockbox\n" && sudo ../travis/configstage.sh

script: printf "\n\nRUNNING MAKE for whiskers75/rockbox\n" && make
after_success: printf "\n\n\nBUILD COMPLETED SUCCESSFULLY"
language: c

env:
   matrix:
      - BUILDTYPE=”N” BUILDFOR=1
      - BUILDTYPE=”N” BUILDFOR=2
      - BUILDTYPE=”N” BUILDFOR=3
      - BUILDTYPE=”N” BUILDFOR=4
      - BUILDTYPE=”N” BUILDFOR=5
      - BUILDTYPE=”N” BUILDFOR=6
      - BUILDTYPE=”N” BUILDFOR=7
      - BUILDTYPE=”N” BUILDFOR=8
      - BUILDTYPE=”N” BUILDFOR=9
      - BUILDTYPE=”N” BUILDFOR=10
      - BUILDTYPE=”N” BUILDFOR=11
      - BUILDTYPE=”N” BUILDFOR=12
      - BUILDTYPE=”N” BUILDFOR=13
      - BUILDTYPE=”N” BUILDFOR=14
      - BUILDTYPE=”N” BUILDFOR=15
      - BUILDTYPE=”N” BUILDFOR=16
      - BUILDTYPE=”N” BUILDFOR=17
      - BUILDTYPE=”N” BUILDFOR=18
      - BUILDTYPE=”N” BUILDFOR=19
      - BUILDTYPE=”N” BUILDFOR=20
      - BUILDTYPE=”N” BUILDFOR=21
      - BUILDTYPE=”N” BUILDFOR=22
      - BUILDTYPE=”N” BUILDFOR=23
      - BUILDTYPE=”N” BUILDFOR=24
      - BUILDTYPE=”N” BUILDFOR=25
      - BUILDTYPE=”N” BUILDFOR=26
      - BUILDTYPE=”N” BUILDFOR=27
      - BUILDTYPE=”N” BUILDFOR=28
      - BUILDTYPE=”N” BUILDFOR=29
      - BUILDTYPE=”N” BUILDFOR=30
      - BUILDTYPE=”N” BUILDFOR=31
      - BUILDTYPE=”N” BUILDFOR=32
      - BUILDTYPE=”N” BUILDFOR=33
      - BUILDTYPE=”N” BUILDFOR=34
      - BUILDTYPE=”N” BUILDFOR=35
      - BUILDTYPE=”N” BUILDFOR=36
      - BUILDTYPE=”N” BUILDFOR=37
      - BUILDTYPE=”N” BUILDFOR=38
      - BUILDTYPE=”N” BUILDFOR=39
      - BUILDTYPE=”N” BUILDFOR=40
      - BUILDTYPE=”N” BUILDFOR=41
      - BUILDTYPE=”N” BUILDFOR=42
      - BUILDTYPE=”N” BUILDFOR=43
      - BUILDTYPE=”N” BUILDFOR=44
      - BUILDTYPE=”N” BUILDFOR=45
      - BUILDTYPE=”N” BUILDFOR=46
      - BUILDTYPE=”N” BUILDFOR=47
      - BUILDTYPE=”N” BUILDFOR=48
      - BUILDTYPE=”N” BUILDFOR=49
      - BUILDTYPE=”N” BUILDFOR=50
      - BUILDTYPE=”N” BUILDFOR=51
      - BUILDTYPE=”N” BUILDFOR=52
      - BUILDTYPE=”N” BUILDFOR=53
      - BUILDTYPE=”N” BUILDFOR=54
      - BUILDTYPE=”N” BUILDFOR=55
      - BUILDTYPE=”N” BUILDFOR=56
      - BUILDTYPE=”N” BUILDFOR=57
      - BUILDTYPE=”N” BUILDFOR=58
      - BUILDTYPE=”N” BUILDFOR=59
      - BUILDTYPE=”N” BUILDFOR=60
      - BUILDTYPE=”N” BUILDFOR=61
      - BUILDTYPE=”N” BUILDFOR=62
      - BUILDTYPE=”N” BUILDFOR=63
      - BUILDTYPE=”N” BUILDFOR=64
      - BUILDTYPE=”N” BUILDFOR=65
      - BUILDTYPE=”N” BUILDFOR=66
      - BUILDTYPE=”N” BUILDFOR=67
      - BUILDTYPE=”N” BUILDFOR=68
      - BUILDTYPE=”N” BUILDFOR=69
      - BUILDTYPE=”N” BUILDFOR=70
      - BUILDTYPE=”N” BUILDFOR=71
      - BUILDTYPE=”N” BUILDFOR=72
      - BUILDTYPE=”N” BUILDFOR=73
      - BUILDTYPE=”N” BUILDFOR=74
      - BUILDTYPE=”N” BUILDFOR=75
      - BUILDTYPE=”N” BUILDFOR=76
      - BUILDTYPE=”N” BUILDFOR=77
      - BUILDTYPE=”N” BUILDFOR=78
      - BUILDTYPE=”N” BUILDFOR=79
      - BUILDTYPE=”N” BUILDFOR=80
      - BUILDTYPE=”N” BUILDFOR=81
      - BUILDTYPE=”N” BUILDFOR=82
      - BUILDTYPE=”N” BUILDFOR=83
      - BUILDTYPE=”N” BUILDFOR=84
      - BUILDTYPE=”N” BUILDFOR=85
      - BUILDTYPE=”N” BUILDFOR=86
      - BUILDTYPE=”N” BUILDFOR=87
      - BUILDTYPE=”N” BUILDFOR=88
      - BUILDTYPE=”N” BUILDFOR=89
      - BUILDTYPE=”N” BUILDFOR=90
      - BUILDTYPE=”N” BUILDFOR=91
      - BUILDTYPE=”N” BUILDFOR=92
      - BUILDTYPE=”N” BUILDFOR=93
      - BUILDTYPE=”N” BUILDFOR=94
      - BUILDTYPE=”N” BUILDFOR=95
      - BUILDTYPE=”N” BUILDFOR=96
      - BUILDTYPE=”N” BUILDFOR=97
      - BUILDTYPE=”N” BUILDFOR=98
      - BUILDTYPE=”N” BUILDFOR=99
      - BUILDTYPE=”N” BUILDFOR=100
      - BUILDTYPE=”N” BUILDFOR=101
      - BUILDTYPE=”N” BUILDFOR=102
      - BUILDTYPE=”N” BUILDFOR=103
      - BUILDTYPE=”N” BUILDFOR=104
      - BUILDTYPE=”N” BUILDFOR=105
      - BUILDTYPE=”N” BUILDFOR=106
      - BUILDTYPE=”N” BUILDFOR=107
      - BUILDTYPE=”N” BUILDFOR=108
      - BUILDTYPE=”N” BUILDFOR=109
      - BUILDTYPE=”N” BUILDFOR=110
      - BUILDTYPE=”N” BUILDFOR=111
      - BUILDTYPE=”N” BUILDFOR=112
      - BUILDTYPE=”N” BUILDFOR=113
      - BUILDTYPE=”N” BUILDFOR=114
      - BUILDTYPE=”N” BUILDFOR=115
      - BUILDTYPE=”N” BUILDFOR=116
      - BUILDTYPE=”N” BUILDFOR=117
      - BUILDTYPE=”N” BUILDFOR=118
      - BUILDTYPE=”N” BUILDFOR=119
      - BUILDTYPE=”N” BUILDFOR=120
      - BUILDTYPE=”N” BUILDFOR=121
      - BUILDTYPE=”N” BUILDFOR=122
      - BUILDTYPE=”N” BUILDFOR=123
      - BUILDTYPE=”N” BUILDFOR=124
      - BUILDTYPE=”N” BUILDFOR=125
      - BUILDTYPE=”N” BUILDFOR=126
      - BUILDTYPE=”N” BUILDFOR=127
      - BUILDTYPE=”N” BUILDFOR=128
      - BUILDTYPE=”N” BUILDFOR=129
      - BUILDTYPE=”N” BUILDFOR=130
      - BUILDTYPE=”N” BUILDFOR=131
      - BUILDTYPE=”N” BUILDFOR=132
      - BUILDTYPE=”N” BUILDFOR=133
      - BUILDTYPE=”N” BUILDFOR=134
      - BUILDTYPE=”N” BUILDFOR=135
      - BUILDTYPE=”N” BUILDFOR=136
      - BUILDTYPE=”N” BUILDFOR=137
      - BUILDTYPE=”N” BUILDFOR=138
      - BUILDTYPE=”N” BUILDFOR=139
      - BUILDTYPE=”N” BUILDFOR=140
      - BUILDTYPE=”N” BUILDFOR=141
      - BUILDTYPE=”N” BUILDFOR=142
      - BUILDTYPE=”N” BUILDFOR=143
      - BUILDTYPE=”N” BUILDFOR=144
      - BUILDTYPE=”N” BUILDFOR=145
      - BUILDTYPE=”N” BUILDFOR=146
      - BUILDTYPE=”N” BUILDFOR=147
      - BUILDTYPE=”N” BUILDFOR=148
      - BUILDTYPE=”N” BUILDFOR=149
      - BUILDTYPE=”N” BUILDFOR=150
      - BUILDTYPE=”N” BUILDFOR=151
      - BUILDTYPE=”N” BUILDFOR=152
      - BUILDTYPE=”N” BUILDFOR=153
      - BUILDTYPE=”N” BUILDFOR=154
      - BUILDTYPE=”N” BUILDFOR=155
      - BUILDTYPE=”N” BUILDFOR=156
      - BUILDTYPE=”N” BUILDFOR=157
      - BUILDTYPE=”N” BUILDFOR=158
      - BUILDTYPE=”N” BUILDFOR=159
      - BUILDTYPE=”N” BUILDFOR=160
      - BUILDTYPE=”N” BUILDFOR=161
      - BUILDTYPE=”N” BUILDFOR=162
      - BUILDTYPE=”N” BUILDFOR=163
      - BUILDTYPE=”N” BUILDFOR=164
      - BUILDTYPE=”N” BUILDFOR=165
      - BUILDTYPE=”N” BUILDFOR=166
      - BUILDTYPE=”N” BUILDFOR=167
      - BUILDTYPE=”N” BUILDFOR=168
      - BUILDTYPE=”N” BUILDFOR=169
      - BUILDTYPE=”N” BUILDFOR=170
      - BUILDTYPE=”N” BUILDFOR=171
      - BUILDTYPE=”N” BUILDFOR=172
      - BUILDTYPE=”N” BUILDFOR=173
      - BUILDTYPE=”N” BUILDFOR=174
      - BUILDTYPE=”N” BUILDFOR=175
      - BUILDTYPE=”N” BUILDFOR=176
      - BUILDTYPE=”N” BUILDFOR=177
      - BUILDTYPE=”N” BUILDFOR=178
      - BUILDTYPE=”N” BUILDFOR=179
      - BUILDTYPE=”N” BUILDFOR=180
      - BUILDTYPE=”N” BUILDFOR=181
      - BUILDTYPE=”N” BUILDFOR=182
      - BUILDTYPE=”N” BUILDFOR=183
      - BUILDTYPE=”N” BUILDFOR=184
      - BUILDTYPE=”N” BUILDFOR=185
      - BUILDTYPE=”N” BUILDFOR=186
      - BUILDTYPE=”N” BUILDFOR=187
      - BUILDTYPE=”N” BUILDFOR=188
      - BUILDTYPE=”N” BUILDFOR=189
      - BUILDTYPE=”N” BUILDFOR=190
      - BUILDTYPE=”N” BUILDFOR=191