before_install:
   - mkdir build
   - cd build
   - sudo apt-get install flex texinfo -qq
   - export BUILDFOR=62
   - echo "Running RockboxDEV Installer"
   - sudo ../tools/rockboxdevquiet.sh > /dev/null
   - echo "Running configure"
   - ../tools/configurequiet > /dev/null

install: make
language: c
