before_script:
   - mkdir build
   - cd build
   - sudo apt-get install flex texinfo -qq
   - export BUILDFOR=62
   - echo "Running configure"
   - ../tools/configurequiet > /dev/null

install: sudo ../tools/rockboxdevquiet.sh > /dev/null

script: make

language: c
