install: printf "\n\nBUILDING whiskers75/rockbox:$TRAVIS_BRANCH $x\nJOB NO $TRAVIS_JOB_ID\nCOMMIT $TRAVIS_COMMIT\nPULL REQUEST $TRAVIS_PULL_REQUEST\n\n\nINSTALLING BUILD DEPENDENCIES FOR ARM TARGETS\n" && while sleep 5; do printf .; done & export 1=$!; sudo travis/installdeps.sh > /dev/null 2>/dev/null &; wait "$!" kill "$1"
before_script:
   - mkdir build && cd build && printf "\n\nCONFIGURING whiskers75/rockbox\n" && while sleep 5; do printf .; done & sudo ../travis/configure.sh; kill "$!"

script: printf "\n\nRUNNING MAKE for whiskers75/rockbox\n" && make

language: c

env:
   secure: "FXkSD4A3wGc1x8ryF1PcFzCHukOdG57T+VWuhYOZna2eYNS7x/y0gsGq6TvF\nJodzHPI7+y+KNtNmhJzfZQDTmeMkabIXU/JLCktmLpi2XA43B/TM17nyIq8k\n1UbOT+B7qinyiAKNx4+b4+uDN+CYaOBVfsiSaHbM8tn6LQp5EzY="
   matrix:
      - Normal Rockbox for Sansa Clip Plus                                                        BUILDTYPE='N' BUILDFOR=62
      - Normal Rockbox for iPod Mini 1st Generation                                               BUILDTYPE='N' BUILDFOR=62
