before_install:
   - mkdir build
   - cd build
   - sudo apt-get install flex texinfo -qq
   - export BUILDFOR=62
   - sudo ../tools/rockboxdevgcc.sh
   - sudo ../tools/rockboxdevbinutils.sh
   - echo "Running configure"
   - ../tools/configurequiet > /dev/null

install: echo "DEPENDENCIES INSTALLED YAY"

script: make

language: c
