before_install: mkdir /tmp/trash

install: sudo travis/installdeps.sh | split -b 1 - /tmp/trash/x | cat /tmp/trash/xaa

before_script:
   - mkdir build && cd build && ../travis/configure.sh

script: printf "\ec\n\nBUILDING whiskers75/rockbox:$TRAVIS_BRANCH $x\nJOB NO $TRAVIS_JOB_ID\nCOMMIT $TRAVIS_COMMIT\nPULL REQUEST $TRAVIS_PULL_REQUEST\n\n" && make

language: c

env:
   matrix:
      - x="Normal Rockbox for Sansa Clip+" BUILDTYPE='N' BUILDFOR=62
      - x="Rockbox Bootloader for Sansa Clip+" BUILDTYPE='B' BUILDFOR=62
