install: printf "\n\nBUILDING whiskers75/rockbox:$TRAVIS_BRANCH $x\nJOB NO $TRAVIS_JOB_ID\nCOMMIT $TRAVIS_COMMIT\nPULL REQUEST $TRAVIS_PULL_REQUEST\n\n\nINSTALLING BUILD DEPENDENCIES FOR ARM TARGETS\n" && sudo travis/installdeps.sh | printf  '.'

before_script:
   - mkdir build && cd build && printf "\n\nCONFIGURING whiskers75/rockbox\n" ../travis/configure.sh | echo -n '.'

script: printf "\n\nRUNNING MAKE for whiskers75/rockbox\n" && make

language: c

env:
   matrix:
      - x="Normal Rockbox for Sansa Clip+" BUILDTYPE='N' BUILDFOR=62
      - x="Rockbox Bootloader for Sansa Clip+" BUILDTYPE='B' BUILDFOR=62
